LOGBOOK.LS     Robot Name ROBOT 16-OCT-22 15:30:18  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Operation        
========================================
FILE 'IRVWAITLOG.VR' is saved          
16-OCT-22 15:30 :18
========================================
FILE 'IRVTRAIN.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'IRVSNAP.VR' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'IRVSAVIR.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'IRVRGTRG.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'IRVRGGTP.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'IRVOVRDANYVP.VR' is saved        
16-OCT-22 15:30 :18
========================================
FILE 'IRVLODIR.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'IRVLEDON.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'IRVLEDOFF.VR' is saved           
16-OCT-22 15:30 :18
========================================
FILE 'IRVHOMING.VR' is saved           
16-OCT-22 15:30 :18
========================================
FILE 'IRVGSEXE.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'IRVGETMSR.VR' is saved           
16-OCT-22 15:30 :18
========================================
FILE 'IRVGETMSL.VR' is saved           
16-OCT-22 15:30 :18
========================================
FILE 'IRVFIND.VR' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'IRVCALDATA.VR' is saved          
16-OCT-22 15:30 :18
========================================
FILE 'IRVBKLSH.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'IRC_STLABEL.VR' is saved         
16-OCT-22 15:30 :18
========================================
FILE 'IRC_STATUS.VR' is saved          
16-OCT-22 15:30 :18
========================================
FILE 'IRC_MSG.VR' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'IRC_COUNTER.VR' is saved         
16-OCT-22 15:30 :18
========================================
FILE 'IPRNGSHO.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'IPRNGSET.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'IPKDMP.ZIP' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'IOSTATUS.CM' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'HTTPKCL.VR' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'HTCOLREC.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'HIST.LS' is saved                
16-OCT-22 15:30 :18
========================================
FILE 'GIGELOG.DG' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'GETDATA.TP' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'GEMDATA.VR' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'FTPLOG.DG' is saved              
16-OCT-22 15:30 :18
========================================
FILE 'FRAMEVAR.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'ETHERNET.DG' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'ERRSYS.LS' is saved              
16-OCT-22 15:30 :18
========================================
FILE 'ERRPWD.LS' is saved              
16-OCT-22 15:30 :18
========================================
FILE 'ERRMOT.LS' is saved              
16-OCT-22 15:30 :18
========================================
FILE 'ERRHIST.LS' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'ERREXT.LS' is saved              
16-OCT-22 15:30 :18
========================================
FILE 'ERRCURR.LS' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'ERRCOMM.LS' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'ERRAPP.LS' is saved              
16-OCT-22 15:30 :18
========================================
FILE 'ERRALL.LS' is saved              
16-OCT-22 15:30 :18
========================================
FILE 'ERRACT.LS' is saved              
16-OCT-22 15:30 :18
========================================
FILE 'EMAIL.DG' is saved               
16-OCT-22 15:30 :18
========================================
FILE 'DIOCFGSV.IO' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'DF_MOTN0.DF' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'DF_LOGI6.DF' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'DF_LOGI5.DF' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'DF_LOGI4.DF' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'DF_LOGI3.DF' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'DF_LOGI2.DF' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'DF_LOGI1.DF' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'DCSVRFY.DG' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'DCSDIFF.DG' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'DCSCHGD3.DG' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'DCSCHGD2.DG' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'DCSCHGD1.DG' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'CONSLOG.DG' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'CONROD2D.VD' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'CONROD2.TP' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'CONROD.TP' is saved              
16-OCT-22 15:30 :18
========================================
FILE 'COMSET.VR' is saved              
16-OCT-22 15:30 :18
========================================
FILE 'CO.TP' is saved                  
16-OCT-22 15:30 :18
========================================
FILE 'CELLIO.SV' is saved              
16-OCT-22 15:30 :18
========================================
FILE 'CAM1CAL.VD' is saved             
16-OCT-22 15:30 :18
========================================
FILE 'CAM.VD' is saved                 
16-OCT-22 15:30 :18
========================================
FILE 'BICSETUP.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'BACKDATE.DT' is saved            
16-OCT-22 15:30 :18
========================================
FILE 'ATERRJOB.VR' is saved            
16-OCT-22 15:30 :18
========================================
FILE '-BCKEDT-.TP' is saved            
16-OCT-22 15:30 :18
========================================
FILE '-BCKED9-.TP' is saved            
16-OCT-22 15:30 :18
========================================
FILE '-BCKED8-.TP' is saved            
16-OCT-22 15:30 :18
========================================
R E S E T                              
                                       
                              00000000 
16-OCT-22 15:30 :14
========================================
FILE 'UPDTLOG.LS' is saved             
16-OCT-22 15:30 :14
========================================
FILE 'UPDATES.DAT' is saved            
16-OCT-22 15:30 :14
========================================
FILE 'TPSCRN.ZIP' is saved             
16-OCT-22 15:30 :14
========================================
FILE 'TPEINS.XML' is saved             
16-OCT-22 15:30 :14
========================================
FILE 'TPACCN.DG' is saved              
16-OCT-22 15:30 :14
========================================
FILE 'TBSWRC65.VR' is saved            
16-OCT-22 15:30 :14
========================================
FILE 'SYSVARS.SV' is saved             
16-OCT-22 15:30 :14
========================================
FILE 'SYSUIF.SV' is saved              
16-OCT-22 15:30 :14
========================================
FILE 'SYSSERVO.SV' is saved            
16-OCT-22 15:30 :14
========================================
FILE 'SYSPASS.SV' is saved             
16-OCT-22 15:30 :14
========================================
FILE 'SYSMAST.SV' is saved             
16-OCT-22 15:30 :14
========================================
FILE 'SYSMACRO.SV' is saved            
16-OCT-22 15:30 :14
========================================
FILE 'SYSHOST.SV' is saved             
16-OCT-22 15:30 :14
========================================
FILE 'SYSFSAC.SV' is saved             
16-OCT-22 15:30 :14
========================================
FILE 'SYSFRAME.SV' is saved            
16-OCT-22 15:30 :14
========================================
FILE 'SWIUPDT.VR' is saved             
16-OCT-22 15:30 :14
========================================
FILE 'SUMMARY.DG' is saved             
16-OCT-22 15:30 :14
========================================
FILE 'STRREG.VR' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'SHADOW.DG' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'SENDSYSV.TP' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'SENDEVNT.TP' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'SENDDATA.TP' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'ROBOTCAM.VD' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'RIPESTAT.DG' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'RIPELOG.DG' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'REQMENU.TP' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'RC65.DT' is saved                
16-OCT-22 15:30 :12
========================================
FILE 'PSRBWLD.CM' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'POSREG.VR' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'PLACE.TP' is saved               
16-OCT-22 15:30 :12
========================================
FILE 'PICKUP.TP' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'ORDERFIL.DAT' is saved           
16-OCT-22 15:30 :12
========================================
FILE 'NUMREG.VR' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'NOTIFY.DG' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'MIXLOGIC.SV' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'MEMCHECK.DG' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'LOGBOOK.LS' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'IRVWAITLOG.VR' is saved          
16-OCT-22 15:30 :12
========================================
FILE 'IRVTRAIN.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'IRVSNAP.VR' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'IRVSAVIR.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'IRVRGTRG.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'IRVRGGTP.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'IRVOVRDANYVP.VR' is saved        
16-OCT-22 15:30 :12
========================================
FILE 'IRVLODIR.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'IRVLEDON.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'IRVLEDOFF.VR' is saved           
16-OCT-22 15:30 :12
========================================
FILE 'IRVHOMING.VR' is saved           
16-OCT-22 15:30 :12
========================================
FILE 'IRVGSEXE.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'IRVGETMSR.VR' is saved           
16-OCT-22 15:30 :12
========================================
FILE 'IRVGETMSL.VR' is saved           
16-OCT-22 15:30 :12
========================================
FILE 'IRVFIND.VR' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'IRVCALDATA.VR' is saved          
16-OCT-22 15:30 :12
========================================
FILE 'IRVBKLSH.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'IRC_STLABEL.VR' is saved         
16-OCT-22 15:30 :12
========================================
FILE 'IRC_STATUS.VR' is saved          
16-OCT-22 15:30 :12
========================================
FILE 'IRC_MSG.VR' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'IRC_COUNTER.VR' is saved         
16-OCT-22 15:30 :12
========================================
FILE 'IPRNGSHO.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'IPRNGSET.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'IPKDMP.ZIP' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'IOSTATUS.CM' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'HTTPKCL.VR' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'HTCOLREC.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'HIST.LS' is saved                
16-OCT-22 15:30 :12
========================================
FILE 'GIGELOG.DG' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'GETDATA.TP' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'GEMDATA.VR' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'FTPLOG.DG' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'FRAMEVAR.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'ETHERNET.DG' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'ERRSYS.LS' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'ERRPWD.LS' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'ERRMOT.LS' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'ERRHIST.LS' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'ERREXT.LS' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'ERRCURR.LS' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'ERRCOMM.LS' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'ERRAPP.LS' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'ERRALL.LS' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'ERRACT.LS' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'EMAIL.DG' is saved               
16-OCT-22 15:30 :12
========================================
FILE 'DIOCFGSV.IO' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'DF_MOTN0.DF' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'DF_LOGI6.DF' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'DF_LOGI5.DF' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'DF_LOGI4.DF' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'DF_LOGI3.DF' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'DF_LOGI2.DF' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'DF_LOGI1.DF' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'DCSVRFY.DG' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'DCSDIFF.DG' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'DCSCHGD3.DG' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'DCSCHGD2.DG' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'DCSCHGD1.DG' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'CONSLOG.DG' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'CONROD2D.VD' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'CONROD2.TP' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'CONROD.TP' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'COMSET.VR' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'CO.TP' is saved                  
16-OCT-22 15:30 :12
========================================
FILE 'CELLIO.SV' is saved              
16-OCT-22 15:30 :12
========================================
FILE 'CAM1CAL.VD' is saved             
16-OCT-22 15:30 :12
========================================
FILE 'CAM.VD' is saved                 
16-OCT-22 15:30 :12
========================================
FILE 'BICSETUP.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'BACKDATE.DT' is saved            
16-OCT-22 15:30 :12
========================================
FILE 'ATERRJOB.VR' is saved            
16-OCT-22 15:30 :12
========================================
FILE '-BCKEDT-.TP' is saved            
16-OCT-22 15:30 :12
========================================
FILE '-BCKED9-.TP' is saved            
16-OCT-22 15:30 :12
========================================
FILE '-BCKED8-.TP' is saved            
16-OCT-22 15:30 :12
========================================
User frame 1(G:1)                      
16-OCT-22 15:29 :36
========================================
User frame 0(G:1)                      
16-OCT-22 15:29 :32
========================================
R E S E T                              
                                       
                              00000000 
16-OCT-22 15:29 :32
========================================
R E S E T                              
                                       
                              00000000 
16-OCT-22 15:29 :32
========================================
User frame 1(G:1)                      
16-OCT-22 15:28 :58
========================================
User frame 0(G:1)                      
16-OCT-22 15:28 :54
========================================
R E S E T                              
                                       
                              00000000 
16-OCT-22 15:28 :54
========================================
R E S E T                              
                                       
                              00000000 
16-OCT-22 15:28 :52
========================================
FILE 'PLACE.TP' is saved               
16-OCT-22 15:28 :52
========================================
FILE 'PLACE.LS' is loaded              
16-OCT-22 15:28 :52
========================================
FILE 'PICKUP.TP' is saved              
16-OCT-22 15:28 :52
========================================
FILE 'PICKUP.LS' is loaded             
16-OCT-22 15:28 :52
========================================
R E S E T                              
                                       
                              00000000 
16-OCT-22 15:28 :50
========================================
Override 100%                          
16-OCT-22 15:28 :50
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
16-OCT-22 15:28 :50
========================================
SYST-043 TP disabled in T1/T2 mode     
                                       
                                       
STOP.L                        00000110 
16-OCT-22 15:28 :50
========================================
'Linear' is selected in 'Motion Modify'
 menu                                  
16-OCT-22 15:28 :06
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  22/23                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
  21:  WAIT    .50(sec)                                                         
  22:J @P[4] 100% FINE                                                          
[End]                                                                           
  22:J @P[4] 100% FINE                                                          
                        [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
16-OCT-22 15:28 :06
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  22/23                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
  21:  WAIT    .50(sec)                                                         
  22:J @P[4] 100% FINE                                                          
[End]                                                                           
                                                                                
                        [CHOICE]                                                
========================================
PREV is pressed                        
16-OCT-22 15:28 :04
========================================
F3( POSID  ) is pressed                
16-OCT-22 15:27 :52
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  22/22                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
  21:  WAIT    .50(sec)                                                         
[End]                                                                           
                                                                                
Paste before this line ?                                                        
         LOGIC   POSID  POSITION CANCEL>                                        
========================================
F5( PASTE  ) is pressed                
16-OCT-22 15:27 :52
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  22/22                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
  21:  WAIT    .50(sec)                                                         
[End]                                                                           
                                                                                
Select lines                                                                    
        SELECT                   PASTE                                          
========================================
F2( COPY   ) is pressed                
16-OCT-22 15:27 :50
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  18/22                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
\\18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
  21:  WAIT    .50(sec)                                                         
[End]                                                                           
                                                                                
Move cursor to select range                                                     
         COPY     CUT            PASTE                                          
========================================
F2(SELECT  ) is pressed                
16-OCT-22 15:27 :48
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  18/22                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
\\18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
  21:  WAIT    .50(sec)                                                         
[End]                                                                           
                                                                                
Select lines                                                                    
        SELECT                   PASTE                                          
========================================
'Copy/Cut' is selected                 
16-OCT-22 15:27 :48
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  18/22                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
\\18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
  21:  WAIT    .50(sec)                                                         
[End]                                                                           
                                                                                
                                                                                
[ INST ]                        |EDCMD|>                                        
========================================
F5([EDCMD]>) is pressed                
16-OCT-22 15:27 :46
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  18/22                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
\\18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
  21:  WAIT    .50(sec)                                                         
[End]                                                                           
                                                                                
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
PREV is pressed                        
16-OCT-22 15:27 :38
========================================
'Copy/Cut' is selected                 
16-OCT-22 15:27 :34
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  19/22                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
\\19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
  21:  WAIT    .50(sec)                                                         
[End]                                                                           
                                                                                
                                                                                
[ INST ]                        |EDCMD|>                                        
========================================
F5([EDCMD]>) is pressed                
16-OCT-22 15:27 :32
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  19/22                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
\\19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
  21:  WAIT    .50(sec)                                                         
[End]                                                                           
                                                                                
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
.50 is entered                         
16-OCT-22 15:27 :26
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  21/22                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
  21:  WAIT \\0.00(sec)                                                         
[End]                                                                           
                                                                                
Old Value: 0                                                                    
        DIRECT INDIRECT[CHOICE]                                                 
========================================
'WAIT ... (sec)' is selected in 'Wait 
statements' menu                      
16-OCT-22 15:27 :22
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  21/22                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
\\21:                                                                           
[End]                                                                           
                                                                                
Select item                                                                     
                       [CHOICE]                                                 
========================================
'WAIT' is selected in 'Instruction' men
u                                      
16-OCT-22 15:27 :22
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  21/22                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
\\21:                                                                           
[End]                                                                           
                                                                                
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
F1([ INST ]) is pressed                
16-OCT-22 15:27 :20
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  21/22                                         
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
  20:  CALL PLACE                                                               
\\21:                                                                           
[End]                                                                           
                                                                                
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
'CALL program' is selected in 'CALL st
atement' menu                         
16-OCT-22 15:27 :14
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  20/22                                         
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
\\20:                                                                           
  21:                                                                           
Select item                                                                     
                       [CHOICE]                                                 
========================================
'CALL' is selected in 'Instruction' men
u                                      
16-OCT-22 15:27 :14
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  20/22                                         
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
\\20:                                                                           
  21:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
F1([ INST ]) is pressed                
16-OCT-22 15:27 :12
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  20/22                                         
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
  19:L  P[3] 3000mm/sec FINE                                                    
\\20:                                                                           
  21:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
'Linear' is selected in 'Motion Modify'
 menu                                  
16-OCT-22 15:26 :58
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  19/22                                         
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
  19:J  P[3] 100% FINE                                                          
  20:                                                                           
  21:                                                                           
  19:J  P[3] 100% FINE                                                          
                        [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
16-OCT-22 15:26 :58
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  19/22                                         
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:J @P[4] 100% FINE                                                          
  19:J  P[3] 100% FINE                                                          
  20:                                                                           
  21:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
'1 J P[] 100% FINE' is selected in 'De
fault Motion' menu                    
16-OCT-22 15:26 :50
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  18/22                                         
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
\\18:                                                                           
  19:J  P[3] 100% FINE                                                          
  20:                                                                           
  21:                                                                           
                                                                                
 ED_DEF                         TOUCHUP>                                        
========================================
F1( POINT  ) is pressed                
16-OCT-22 15:26 :48
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  18/22                                         
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
\\18:                                                                           
  19:J  P[3] 100% FINE                                                          
  20:                                                                           
  21:                                                                           
                                                                                
 POINT                          TOUCHUP>                                        
========================================
SHIFT,+Z(J3) is pressed                
16-OCT-22 15:26 :06
========================================
'1 J P[] 100% FINE' is selected in 'De
fault Motion' menu                    
16-OCT-22 15:25 :46
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  19/22                                         
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:                                                                           
\\19:                                                                           
  20:                                                                           
                                                                                
 ED_DEF                         TOUCHUP>                                        
========================================
F1( POINT  ) is pressed                
16-OCT-22 15:25 :40
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  19/22                                         
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:                                                                           
\\19:                                                                           
  20:                                                                           
                                                                                
 POINT                          TOUCHUP>                                        
========================================
PREV is pressed                        
16-OCT-22 15:25 :38
========================================
F1([ INST ]) is pressed                
16-OCT-22 15:25 :36
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  19/22                                         
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  18:                                                                           
\\19:                                                                           
  20:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
PREV is pressed                        
16-OCT-22 15:23 :52
========================================
F3( POSID  ) is pressed                
16-OCT-22 15:23 :00
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  17/21                                         
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\17:                                                                           
  18:                                                                           
Paste before this line ?                                                        
         LOGIC   POSID  POSITION CANCEL>                                        
========================================
F5( PASTE  ) is pressed                
16-OCT-22 15:22 :58
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  17/21                                         
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\17:                                                                           
  18:                                                                           
Select lines                                                                    
        SELECT                   PASTE                                          
========================================
F2( COPY   ) is pressed                
16-OCT-22 15:22 :54
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  13/21                                         
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
\\13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:                                                                           
  18:                                                                           
Move cursor to select range                                                     
         COPY     CUT            PASTE                                          
========================================
F2(SELECT  ) is pressed                
16-OCT-22 15:22 :46
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  13/21                                         
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
\\13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  17:                                                                           
  18:                                                                           
Select lines                                                                    
        SELECT                   PASTE                                          
========================================
F3( POSID  ) is pressed                
16-OCT-22 15:22 :36
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  16/20                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
\\16:                                                                           
  17:                                                                           
Paste before this line ?                                                        
         LOGIC   POSID  POSITION CANCEL>                                        
========================================
F5( PASTE  ) is pressed                
16-OCT-22 15:22 :34
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  16/20                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
\\16:                                                                           
  17:                                                                           
Select lines                                                                    
        SELECT                   PASTE                                          
========================================
F2( COPY   ) is pressed                
16-OCT-22 15:22 :28
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  10/20                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
\\10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:                                                                           
  17:                                                                           
Move cursor to select range                                                     
         COPY     CUT            PASTE                                          
========================================
F2(SELECT  ) is pressed                
16-OCT-22 15:22 :26
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  10/20                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
\\10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:                                                                           
  17:                                                                           
Select lines                                                                    
        SELECT                   PASTE                                          
========================================
'Copy/Cut' is selected                 
16-OCT-22 15:22 :26
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  10/20                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
\\10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:                                                                           
  17:                                                                           
                                                                                
[ INST ]                        |EDCMD|>                                        
========================================
F5([EDCMD]>) is pressed                
16-OCT-22 15:22 :24
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  10/20                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
\\10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT    .50(sec)                                                         
  16:                                                                           
  17:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
0.50 is entered                        
16-OCT-22 15:22 :20
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  15/20                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
  15:  WAIT \\0.00(sec)                                                         
  16:                                                                           
  17:                                                                           
Old Value: 0                                                                    
        DIRECT INDIRECT[CHOICE]                                                 
========================================
'WAIT ... (sec)' is selected in 'Wait 
statements' menu                      
16-OCT-22 15:22 :16
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  15/20                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
\\15:                                                                           
  16:                                                                           
  17:                                                                           
Select item                                                                     
                       [CHOICE]                                                 
========================================
'WAIT' is selected in 'Instruction' men
u                                      
16-OCT-22 15:22 :14
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  15/20                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
\\15:                                                                           
  16:                                                                           
  17:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
F1([ INST ]) is pressed                
16-OCT-22 15:22 :12
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  15/20                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
\\15:                                                                           
  16:                                                                           
  17:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
F1([ INST ]) is pressed                
16-OCT-22 15:22 :12
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  15/20                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
\\15:                                                                           
  16:                                                                           
  17:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
F1([ INST ]) is pressed                
16-OCT-22 15:22 :10
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  15/20                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:  CALL PICKUP                                                              
\\15:                                                                           
  16:                                                                           
  17:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
R E S E T                              
                                       
                              00000000 
16-OCT-22 15:22 :10
========================================
FILE 'UPDTLOG.LS' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'UPDATES.DAT' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'TPSCRN.ZIP' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'TPEINS.XML' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'TPACCN.DG' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'TBSWRC65.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'SYSVARS.SV' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'SYSUIF.SV' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'SYSSERVO.SV' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'SYSPASS.SV' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'SYSMAST.SV' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'SYSMACRO.SV' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'SYSHOST.SV' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'SYSFSAC.SV' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'SYSFRAME.SV' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'SWIUPDT.VR' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'SUMMARY.DG' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'STRREG.VR' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'SHADOW.DG' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'SENDSYSV.TP' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'SENDEVNT.TP' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'SENDDATA.TP' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'ROBOTCAM.VD' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'RIPESTAT.DG' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'RIPELOG.DG' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'REQMENU.TP' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'RC65.DT' is saved                
16-OCT-22 15:22 :10
========================================
FILE 'PSRBWLD.CM' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'POSREG.VR' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'PLACE.TP' is saved               
16-OCT-22 15:22 :10
========================================
FILE 'PICKUP.TP' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'ORDERFIL.DAT' is saved           
16-OCT-22 15:22 :10
========================================
FILE 'NUMREG.VR' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'NOTIFY.DG' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'MIXLOGIC.SV' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'MEMCHECK.DG' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'LOGBOOK.LS' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'IRVWAITLOG.VR' is saved          
16-OCT-22 15:22 :10
========================================
FILE 'IRVTRAIN.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'IRVSNAP.VR' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'IRVSAVIR.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'IRVRGTRG.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'IRVRGGTP.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'IRVOVRDANYVP.VR' is saved        
16-OCT-22 15:22 :10
========================================
FILE 'IRVLODIR.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'IRVLEDON.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'IRVLEDOFF.VR' is saved           
16-OCT-22 15:22 :10
========================================
FILE 'IRVHOMING.VR' is saved           
16-OCT-22 15:22 :10
========================================
FILE 'IRVGSEXE.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'IRVGETMSR.VR' is saved           
16-OCT-22 15:22 :10
========================================
FILE 'IRVGETMSL.VR' is saved           
16-OCT-22 15:22 :10
========================================
FILE 'IRVFIND.VR' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'IRVCALDATA.VR' is saved          
16-OCT-22 15:22 :10
========================================
FILE 'IRVBKLSH.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'IRC_STLABEL.VR' is saved         
16-OCT-22 15:22 :10
========================================
FILE 'IRC_STATUS.VR' is saved          
16-OCT-22 15:22 :10
========================================
FILE 'IRC_MSG.VR' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'IRC_COUNTER.VR' is saved         
16-OCT-22 15:22 :10
========================================
FILE 'IPRNGSHO.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'IPRNGSET.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'IPKDMP.ZIP' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'IOSTATUS.CM' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'HTTPKCL.VR' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'HTCOLREC.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'HIST.LS' is saved                
16-OCT-22 15:22 :10
========================================
FILE 'GIGELOG.DG' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'GETDATA.TP' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'GEMDATA.VR' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'FTPLOG.DG' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'FRAMEVAR.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'ETHERNET.DG' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'ERRSYS.LS' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'ERRPWD.LS' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'ERRMOT.LS' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'ERRHIST.LS' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'ERREXT.LS' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'ERRCURR.LS' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'ERRCOMM.LS' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'ERRAPP.LS' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'ERRALL.LS' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'ERRACT.LS' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'EMAIL.DG' is saved               
16-OCT-22 15:22 :10
========================================
FILE 'DIOCFGSV.IO' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'DF_MOTN0.DF' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'DF_LOGI6.DF' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'DF_LOGI5.DF' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'DF_LOGI4.DF' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'DF_LOGI3.DF' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'DF_LOGI2.DF' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'DF_LOGI1.DF' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'DCSVRFY.DG' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'DCSDIFF.DG' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'DCSCHGD3.DG' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'DCSCHGD2.DG' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'DCSCHGD1.DG' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'CONSLOG.DG' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'CONROD2D.VD' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'CONROD2.TP' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'CONROD.TP' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'COMSET.VR' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'CO.TP' is saved                  
16-OCT-22 15:22 :10
========================================
FILE 'CELLIO.SV' is saved              
16-OCT-22 15:22 :10
========================================
FILE 'CAM1CAL.VD' is saved             
16-OCT-22 15:22 :10
========================================
FILE 'CAM.VD' is saved                 
16-OCT-22 15:22 :10
========================================
FILE 'BICSETUP.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'BACKDATE.DT' is saved            
16-OCT-22 15:22 :10
========================================
FILE 'ATERRJOB.VR' is saved            
16-OCT-22 15:22 :10
========================================
FILE '-BCKEDT-.TP' is saved            
16-OCT-22 15:22 :10
========================================
FILE '-BCKED9-.TP' is saved            
16-OCT-22 15:22 :10
========================================
FILE '-BCKED8-.TP' is saved            
16-OCT-22 15:22 :10
========================================
'CALL program' is selected in 'CALL st
atement' menu                         
16-OCT-22 15:22 :00
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  14/20                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
\\14:                                                                           
  15:                                                                           
Select item                                                                     
                       [CHOICE]                                                 
========================================
'CALL' is selected in 'Instruction' men
u                                      
16-OCT-22 15:22 :00
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  14/20                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
\\14:                                                                           
  15:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
F1([ INST ]) is pressed                
16-OCT-22 15:21 :58
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  14/20                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J  P[2] 3% FINE Offset,PR[2]                                               
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
\\14:                                                                           
  15:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
'Joint' is selected in 'Motion Modify' 
menu                                   
16-OCT-22 15:21 :34
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/20                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:                                                                           
  11:L  P[2] 100mm/sec FINE                                                     
                        [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
16-OCT-22 15:21 :32
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/20                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
PREV is pressed                        
16-OCT-22 15:21 :30
========================================
PREV is pressed                        
16-OCT-22 15:21 :30
========================================
F2(SELECT  ) is pressed                
16-OCT-22 15:21 :28
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/20                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  14:                                                                           
Select lines                                                                    
        SELECT                   PASTE                                          
========================================
F3( POSID  ) is pressed                
16-OCT-22 15:21 :16
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  13/19                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
\\13:                                                                           
  14:                                                                           
  15:                                                                           
Paste before this line ?                                                        
         LOGIC   POSID  POSITION CANCEL>                                        
========================================
F5( PASTE  ) is pressed                
16-OCT-22 15:21 :14
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  13/19                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
\\13:                                                                           
  14:                                                                           
  15:                                                                           
Select lines                                                                    
        SELECT                   PASTE                                          
========================================
F2( COPY   ) is pressed                
16-OCT-22 15:21 :12
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/19                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:                                                                           
  14:                                                                           
  15:                                                                           
Move cursor to select range                                                     
         COPY     CUT            PASTE                                          
========================================
F2(SELECT  ) is pressed                
16-OCT-22 15:21 :10
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/19                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:                                                                           
  14:                                                                           
  15:                                                                           
Select lines                                                                    
        SELECT                   PASTE                                          
========================================
'Copy/Cut' is selected                 
16-OCT-22 15:21 :10
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/19                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:                                                                           
  14:                                                                           
  15:                                                                           
                                                                                
[ INST ]                        |EDCMD|>                                        
========================================
F5([EDCMD]>) is pressed                
16-OCT-22 15:21 :08
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/19                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:  PR[2,3]=PR[2,3]-R[1:APPR]                                                
  13:                                                                           
  14:                                                                           
  15:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
'-' is selected in 'REGISTER statement'
 menu                                  
16-OCT-22 15:20 :44
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  12/19                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  13:                                                                           
  14:                                                                           
  15:                                                                           
  12:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
                       [CHOICE]                                                 
========================================
F4(CHOICE] ) is pressed                
16-OCT-22 15:20 :44
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  12/19                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  13:                                                                           
  14:                                                                           
  15:                                                                           
                                                                                
                       [CHOICE]                                                 
========================================
PREV is pressed                        
16-OCT-22 15:20 :26
========================================
F3( POSID  ) is pressed                
16-OCT-22 15:20 :14
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  12/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
\\12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
Paste before this line ?                                                        
         LOGIC   POSID  POSITION CANCEL>                                        
========================================
F5( PASTE  ) is pressed                
16-OCT-22 15:20 :12
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  12/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
\\12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
Move cursor to select range                                                     
         COPY     CUT            PASTE                                          
========================================
F2(SELECT  ) is pressed                
16-OCT-22 15:20 :10
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  12/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
\\12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
Select lines                                                                    
        SELECT                   PASTE                                          
========================================
F2( COPY   ) is pressed                
16-OCT-22 15:20 :06
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  10/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
\\10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
Move cursor to select range                                                     
         COPY     CUT            PASTE                                          
========================================
F2(SELECT  ) is pressed                
16-OCT-22 15:20 :06
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  10/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
\\10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
Select lines                                                                    
        SELECT                   PASTE                                          
========================================
'Copy/Cut' is selected                 
16-OCT-22 15:20 :04
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  10/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
\\10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
                                                                                
[ INST ]                        |EDCMD|>                                        
========================================
F5([EDCMD]>) is pressed                
16-OCT-22 15:20 :04
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  10/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
\\10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[2]                                                             
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
2 is entered                           
16-OCT-22 15:19 :08
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE                                                     
    :  Offset,PR[...] ]                                                         
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
Old Value: 0                                                                    
        DIRECT INDIRECT[CHOICE] [LIST]                                          
========================================
'Offset,PR[  ]' is selected in 'Motion
 Modify' menu                         
16-OCT-22 15:18 :58
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE\\\                                                  
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  11:L  P[2] 100mm/sec FINE\\\                                                  
                        [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
16-OCT-22 15:18 :38
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L  P[2] 100mm/sec FINE\\\                                                  
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
F4(  DONE  ) is pressed                
16-OCT-22 15:18 :18
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X \\\\\0.000   mm  W      0.000  deg                                           
 Y      0.000   mm  P      0.000  deg                                           
 Z      0.000   mm  R      0.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L \P[2] 100mm/sec FINE                                                     
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
0 is entered                           
16-OCT-22 15:18 :16
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X      0.000   mm  W      0.000  deg                                           
 Y      0.000   mm  P      0.000  deg                                           
 Z      0.000   mm  R \\\\\-.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L \P[2] 100mm/sec FINE                                                     
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
0 is entered                           
16-OCT-22 15:18 :14
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X      0.000   mm  W      0.000  deg                                           
 Y      0.000   mm  P \\\\\\.000  deg                                           
 Z      0.000   mm  R      -.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L \P[2] 100mm/sec FINE                                                     
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
0 is entered                           
16-OCT-22 15:18 :14
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X      0.000   mm  W \\\\\\.000  deg                                           
 Y      0.000   mm  P       .000  deg                                           
 Z      0.000   mm  R      -.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L \P[2] 100mm/sec FINE                                                     
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
0 is entered                           
16-OCT-22 15:18 :14
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X      0.000   mm  W       .000  deg                                           
 Y      0.000   mm  P       .000  deg                                           
 Z \\\367.000   mm  R      -.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L \P[2] 100mm/sec FINE                                                     
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
0 is entered                           
16-OCT-22 15:18 :12
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X      0.000   mm  W       .000  deg                                           
 Y \\\500.000   mm  P       .000  deg                                           
 Z    367.000   mm  R      -.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L @P[2] 100mm/sec FINE                                                     
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
0 is entered                           
16-OCT-22 15:18 :12
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X \-1065.687   mm  W       .000  deg                                           
 Y    500.000   mm  P       .000  deg                                           
 Z    367.000   mm  R      -.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L @P[2] 100mm/sec FINE                                                     
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
F5(POSITION) is pressed                
16-OCT-22 15:18 :08
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:L @P[2] 100mm/sec FINE                                                     
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value or press ENTER                                                      
                        [CHOICE]POSITION                                        
========================================
PREV is pressed                        
16-OCT-22 15:18 :06
========================================
ENTER is pressed                       
16-OCT-22 15:18 :02
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
16-OCT-22 15:17 :58
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
                                                                                
 ED_DEF                         TOUCHUP>                                        
========================================
F1( POINT  ) is pressed                
16-OCT-22 15:17 :56
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
                                                                                
 POINT                          TOUCHUP>                                        
========================================
PREV is pressed                        
16-OCT-22 15:17 :54
========================================
F1([ INST ]) is pressed                
16-OCT-22 15:17 :46
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/18                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
2 is entered                           
16-OCT-22 15:17 :42
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/16                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
[End]                                                                           
How many line to insert ? :                                                     
                                                                                
========================================
'Insert' is selected                   
16-OCT-22 15:17 :38
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/16                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
[End]                                                                           
                                                                                
[ INST ]                        |EDCMD|>                                        
========================================
F5([EDCMD]>) is pressed                
16-OCT-22 15:17 :38
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/16                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
[End]                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
F4(  YES   ) is pressed                
16-OCT-22 15:17 :36
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/17                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\11:J  P[2] 100% CNT100                                                        
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Delete line(s) ?                                                                
                          YES     NO                                            
========================================
'Delete' is selected                   
16-OCT-22 15:17 :34
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/17                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
\\11:J  P[2] 100% CNT100                                                        
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
                                                                                
[ INST ]                        |EDCMD|>                                        
========================================
PREV is pressed                        
16-OCT-22 15:17 :30
========================================
R E S E T                              
                                       
                              00000000 
16-OCT-22 15:17 :26
========================================
RESET is pressed                       
16-OCT-22 15:17 :26
========================================
F4(  DONE  ) is pressed                
16-OCT-22 15:17 :04
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X \\\\\0.000   mm  W      0.000  deg                                           
 Y      0.000   mm  P      0.000  deg                                           
 Z      0.000   mm  R      0.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J \P[2] 100% CNT100                                                        
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
0 is entered                           
16-OCT-22 15:17 :00
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X      0.000   mm  W      0.000  deg                                           
 Y      0.000   mm  P      0.000  deg                                           
 Z      0.000   mm  R \\\\\-.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J \P[2] 100% CNT100                                                        
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
0 is entered                           
16-OCT-22 15:17 :00
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X      0.000   mm  W      0.000  deg                                           
 Y      0.000   mm  P \\\\\\.000  deg                                           
 Z      0.000   mm  R      -.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J \P[2] 100% CNT100                                                        
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
0 is entered                           
16-OCT-22 15:16 :58
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X      0.000   mm  W \\\\\\.000  deg                                           
 Y      0.000   mm  P       .000  deg                                           
 Z      0.000   mm  R      -.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J \P[2] 100% CNT100                                                        
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
0 is entered                           
16-OCT-22 15:16 :54
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X      0.000   mm  W       .000  deg                                           
 Y      0.000   mm  P       .000  deg                                           
 Z \\\367.000   mm  R      -.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J \P[2] 100% CNT100                                                        
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
0 is entered                           
16-OCT-22 15:16 :54
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X      0.000   mm  W       .000  deg                                           
 Y \\\500.000   mm  P       .000  deg                                           
 Z    367.000   mm  R      -.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J @P[2] 100% CNT100                                                        
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
0 is entered                           
16-OCT-22 15:16 :50
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X \-1065.687   mm  W       .000  deg                                           
 Y    500.000   mm  P       .000  deg                                           
 Z    367.000   mm  R      -.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J @P[2] 100% CNT100                                                        
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
F5(POSITION) is pressed                
16-OCT-22 15:16 :50
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                  11/17                                         
   7:  VISION GET_OFFSET 'CONROD2D'                                             
    :  VR[1] JMP LBL[1]                                                         
   8:  PR[2]=VR[1].FOUND_POS[1]                                                 
   9:  UFRAME_NUM=1                                                             
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J @P[2] 100% CNT100                                                        
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value or press ENTER                                                      
                        [CHOICE]POSITION                                        
========================================
F4(  DONE  ) is pressed                
16-OCT-22 15:16 :44
--Screen image--------------------------
                                                                                
CONROD2           LINE 0    \T2\ ABORTED\\\\\\\\\\\WORLD\\\\\\                  
CONROD2\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
 P[2] UF:1  UT:1         CONF:NUT 000                                           
 X \-1065.687   mm  W       .000  deg                                           
 Y    500.000   mm  P       .000  deg                                           
 Z    367.000   mm  R      -.000  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
  10:  PR[2,3]=PR[2,3]+R[1:APPR]                                                
  11:J @P[2] 100% CNT100                                                        
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
I/O              
========================================
 UO[    1]    ON  -> OFF
Tick:   3819749
TB:     1013755840
16-OCT-22 15:30 :06
========================================
 SO[    0]    ON  -> OFF
Tick:   3819744
TB:     1013710349
16-OCT-22 15:30 :06
========================================
 SO[    1]    ON  -> OFF
Tick:   3819492
TB:     1009128847
16-OCT-22 15:30 :06
========================================
 UO[   18]    ON  -> OFF
Tick:   3819491
TB:     1009113440
16-OCT-22 15:30 :06
========================================
 UO[    3]    ON  -> OFF
Tick:   3819490
TB:     1009084323
16-OCT-22 15:30 :06
========================================
Aborted      CONROD2     ,   0         
 (TASK:5,TB:1008902947)                
16-OCT-22 15:30 :06
========================================
Run FWD      CONROD2     ,  22         
 (TASK:5,TB:1005176802)                
16-OCT-22 15:30 :06
========================================
Run FWD      CONROD2     ,  21         
 (TASK:5,TB:999302099)                 
16-OCT-22 15:30 :04
========================================
Run FWD      PLACE       ,   6         
 (TASK:5,TB:999301812)                 
16-OCT-22 15:30 :04
========================================
Run FWD      PLACE       ,   5         
 (TASK:5,TB:999301701)                 
16-OCT-22 15:30 :04
========================================
Run FWD      PLACE       ,   4         
 (TASK:5,TB:999301590)                 
16-OCT-22 15:30 :04
========================================
Run FWD      PLACE       ,   3         
 (TASK:5,TB:999301478)                 
16-OCT-22 15:30 :04
========================================
Run FWD      PLACE       ,   2         
 (TASK:5,TB:999301366)                 
16-OCT-22 15:30 :04
========================================
Run FWD      PLACE       ,   1         
 (TASK:5,TB:999301248)                 
16-OCT-22 15:30 :04
========================================
Run FWD      CONROD2     ,  20         
 (TASK:5,TB:999300591)                 
16-OCT-22 15:30 :04
========================================
Run FWD      CONROD2     ,  19         
 (TASK:5,TB:995623756)                 
16-OCT-22 15:30 :04
========================================
Run FWD      CONROD2     ,  18         
 (TASK:5,TB:977433348)                 
16-OCT-22 15:30 :02
========================================
Run FWD      CONROD2     ,  17         
 (TASK:5,TB:954289197)                 
16-OCT-22 15:30 :00
========================================
Run FWD      CONROD2     ,  16         
 (TASK:5,TB:954288940)                 
16-OCT-22 15:30 :00
========================================
Run FWD      CONROD2     ,  15         
 (TASK:5,TB:948547249)                 
16-OCT-22 15:30 :00
========================================
Run FWD      PICKUP      ,   6         
 (TASK:5,TB:948546963)                 
16-OCT-22 15:30 :00
========================================
Run FWD      PICKUP      ,   5         
 (TASK:5,TB:948546851)                 
16-OCT-22 15:30 :00
========================================
Run FWD      PICKUP      ,   4         
 (TASK:5,TB:948546738)                 
16-OCT-22 15:30 :00
========================================
Run FWD      PICKUP      ,   3         
 (TASK:5,TB:948546627)                 
16-OCT-22 15:30 :00
========================================
Run FWD      PICKUP      ,   2         
 (TASK:5,TB:948546514)                 
16-OCT-22 15:30 :00
========================================
Run FWD      PICKUP      ,   1         
 (TASK:5,TB:948546395)                 
16-OCT-22 15:30 :00
========================================
Run FWD      CONROD2     ,  14         
 (TASK:5,TB:948545734)                 
16-OCT-22 15:30 :00
========================================
Run FWD      CONROD2     ,  13         
 (TASK:5,TB:925475013)                 
16-OCT-22 15:29 :58
========================================
Run FWD      CONROD2     ,  12         
 (TASK:5,TB:925474756)                 
16-OCT-22 15:29 :58
========================================
Run FWD      CONROD2     ,  11         
 (TASK:5,TB:701486356)                 
16-OCT-22 15:29 :36
========================================
Run FWD      CONROD2     ,  10         
 (TASK:5,TB:701486156)                 
16-OCT-22 15:29 :36
========================================
Run FWD      CONROD2     ,   9         
 (TASK:5,TB:701486010)                 
16-OCT-22 15:29 :36
========================================
Run FWD      CONROD2     ,   8         
 (TASK:5,TB:701485784)                 
16-OCT-22 15:29 :36
========================================
Run FWD      CONROD2     ,   7         
 (TASK:5,TB:701445824)                 
16-OCT-22 15:29 :36
========================================
Run FWD      CONROD2     ,   6         
 (TASK:5,TB:689774479)                 
16-OCT-22 15:29 :34
========================================
Run FWD      CONROD2     ,   5         
 (TASK:5,TB:689774306)                 
16-OCT-22 15:29 :34
========================================
 SO[    0]    OFF -> ON 
Tick:   3804099
TB:     673762322
16-OCT-22 15:29 :32
========================================
 UO[    1]    OFF -> ON 
Tick:   3804097
TB:     673742890
16-OCT-22 15:29 :32
========================================
 SO[    1]    OFF -> ON 
Tick:   3804036
TB:     673110450
16-OCT-22 15:29 :32
========================================
 UO[   18]    OFF -> ON 
Tick:   3804035
TB:     673092771
16-OCT-22 15:29 :32
========================================
 UO[    3]    OFF -> ON 
Tick:   3804034
TB:     673082931
16-OCT-22 15:29 :32
========================================
Run FWD      CONROD2     ,   4         
 (TASK:5,TB:672661437)                 
16-OCT-22 15:29 :32
========================================
Run FWD      CONROD2     ,   3         
 (TASK:5,TB:672661323)                 
16-OCT-22 15:29 :32
========================================
Run FWD      CONROD2     ,   2         
 (TASK:5,TB:672661175)                 
16-OCT-22 15:29 :32
========================================
Run FWD      CONROD2     ,   1         
 (TASK:5,TB:672657024)                 
16-OCT-22 15:29 :32
========================================
 SI[    1]    ON  -> OFF
Tick:   3803980
TB:     671996757
16-OCT-22 15:29 :32
========================================
 SI[    1]    OFF -> ON 
Tick:   3803287
TB:     664912477
16-OCT-22 15:29 :32
========================================
 SO[    0]    ON  -> OFF
Tick:   3798436
TB:     613817379
16-OCT-22 15:29 :26
========================================
 UO[    1]    ON  -> OFF
Tick:   3798434
TB:     613790462
16-OCT-22 15:29 :26
========================================
 UO[    3]    ON  -> OFF
Tick:   3798182
TB:     609401531
16-OCT-22 15:29 :26
========================================
 SO[    1]    ON  -> OFF
Tick:   3798177
TB:     609307006
16-OCT-22 15:29 :26
========================================
 UO[   18]    ON  -> OFF
Tick:   3798176
TB:     609283527
16-OCT-22 15:29 :26
========================================
Aborted      CONROD2     ,   0         
 (TASK:5,TB:608538131)                 
16-OCT-22 15:29 :26
========================================
Run FWD      CONROD2     ,  22         
 (TASK:5,TB:604730869)                 
16-OCT-22 15:29 :26
========================================
Run FWD      CONROD2     ,  21         
 (TASK:5,TB:599176232)                 
16-OCT-22 15:29 :24
========================================
Run FWD      PLACE       ,   6         
 (TASK:5,TB:599175946)                 
16-OCT-22 15:29 :24
========================================
Run FWD      PLACE       ,   5         
 (TASK:5,TB:599175836)                 
16-OCT-22 15:29 :24
========================================
Run FWD      PLACE       ,   4         
 (TASK:5,TB:599175725)                 
16-OCT-22 15:29 :24
========================================
Run FWD      PLACE       ,   3         
 (TASK:5,TB:599175615)                 
16-OCT-22 15:29 :24
========================================
Run FWD      PLACE       ,   2         
 (TASK:5,TB:599175503)                 
16-OCT-22 15:29 :24
========================================
Run FWD      PLACE       ,   1         
 (TASK:5,TB:599175388)                 
16-OCT-22 15:29 :24
========================================
Run FWD      CONROD2     ,  20         
 (TASK:5,TB:599174717)                 
16-OCT-22 15:29 :24
========================================
Run FWD      CONROD2     ,  19         
 (TASK:5,TB:595491306)                 
16-OCT-22 15:29 :24
========================================
Run FWD      CONROD2     ,  18         
 (TASK:5,TB:577485833)                 
16-OCT-22 15:29 :22
========================================
Run FWD      CONROD2     ,  17         
 (TASK:5,TB:554221513)                 
16-OCT-22 15:29 :20
========================================
Run FWD      CONROD2     ,  16         
 (TASK:5,TB:554221262)                 
16-OCT-22 15:29 :20
========================================
Run FWD      CONROD2     ,  15         
 (TASK:5,TB:547836384)                 
16-OCT-22 15:29 :20
========================================
Run FWD      PICKUP      ,   6         
 (TASK:5,TB:547836101)                 
16-OCT-22 15:29 :20
========================================
Run FWD      PICKUP      ,   5         
 (TASK:5,TB:547835990)                 
16-OCT-22 15:29 :20
========================================
Run FWD      PICKUP      ,   4         
 (TASK:5,TB:547835878)                 
16-OCT-22 15:29 :20
========================================
Run FWD      PICKUP      ,   3         
 (TASK:5,TB:547835767)                 
16-OCT-22 15:29 :20
========================================
Run FWD      PICKUP      ,   2         
 (TASK:5,TB:547835652)                 
16-OCT-22 15:29 :20
========================================
Run FWD      PICKUP      ,   1         
 (TASK:5,TB:547835224)                 
16-OCT-22 15:29 :20
========================================
Run FWD      CONROD2     ,  14         
 (TASK:5,TB:547834564)                 
16-OCT-22 15:29 :20
========================================
Run FWD      CONROD2     ,  13         
 (TASK:5,TB:524708408)                 
16-OCT-22 15:29 :18
========================================
Run FWD      CONROD2     ,  12         
 (TASK:5,TB:524708148)                 
16-OCT-22 15:29 :18
========================================
Run FWD      CONROD2     ,  11         
 (TASK:5,TB:321274445)                 
16-OCT-22 15:28 :58
========================================
Run FWD      CONROD2     ,  10         
 (TASK:5,TB:321274135)                 
16-OCT-22 15:28 :58
========================================
Run FWD      CONROD2     ,   9         
 (TASK:5,TB:321273995)                 
16-OCT-22 15:28 :58
========================================
Run FWD      CONROD2     ,   8         
 (TASK:5,TB:321273725)                 
16-OCT-22 15:28 :58
========================================
Run FWD      CONROD2     ,   7         
 (TASK:5,TB:321233646)                 
16-OCT-22 15:28 :58
========================================
Run FWD      CONROD2     ,   6         
 (TASK:5,TB:306143102)                 
16-OCT-22 15:28 :56
========================================
Run FWD      CONROD2     ,   5         
 (TASK:5,TB:306142924)                 
16-OCT-22 15:28 :56
========================================
 SO[    0]    OFF -> ON 
Tick:   3783589
TB:     283023041
16-OCT-22 15:28 :54
========================================
 UO[    1]    OFF -> ON 
Tick:   3783587
TB:     283003542
16-OCT-22 15:28 :54
========================================
 SO[    1]    OFF -> ON 
Tick:   3783491
TB:     282023164
16-OCT-22 15:28 :54
========================================
 UO[   18]    OFF -> ON 
Tick:   3783490
TB:     282017479
16-OCT-22 15:28 :54
========================================
 UO[    3]    OFF -> ON 
Tick:   3783489
TB:     282016983
16-OCT-22 15:28 :54
========================================
Run FWD      CONROD2     ,   4         
 (TASK:5,TB:281483537)                 
16-OCT-22 15:28 :54
========================================
Run FWD      CONROD2     ,   3         
 (TASK:5,TB:281483413)                 
16-OCT-22 15:28 :54
========================================
Run FWD      CONROD2     ,   2         
 (TASK:5,TB:281480329)                 
16-OCT-22 15:28 :54
========================================
Run FWD      CONROD2     ,   1         
 (TASK:5,TB:281416697)                 
16-OCT-22 15:28 :54
========================================
 SI[    1]    ON  -> OFF
Tick:   3783435
TB:     280211500
16-OCT-22 15:28 :54
========================================
 SI[    1]    OFF -> ON 
Tick:   3782707
TB:     272741457
16-OCT-22 15:28 :52
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   3781445
TB:     258325787
16-OCT-22 15:28 :50
========================================
 SO[    3]    ON  -> OFF
Tick:   3781440
TB:     258277782
16-OCT-22 15:28 :50
========================================
 SO[    3]    OFF -> ON 
Tick:   3781125
TB:     255072537
16-OCT-22 15:28 :50
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   3781123
TB:     255053204
16-OCT-22 15:28 :50
========================================
 SO[    7]    ON  -> OFF
Tick:   3781090
TB:     254719278
16-OCT-22 15:28 :50
========================================
 UO[    8]    ON  -> OFF
Tick:   3781088
TB:     254717384
16-OCT-22 15:28 :50
========================================
 SO[    3]    ON  -> OFF
Tick:   1829378
TB:     1348329776
16-OCT-22 14:54 :52
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   1829376
TB:     1348315503
16-OCT-22 14:54 :52
========================================
 UO[    2]    ON  -> OFF
Tick:   1717824
TB:     184699221
16-OCT-22 14:52 :56
========================================
 SO[    3]    OFF -> ON 
Tick:   1717798
TB:     184424009
16-OCT-22 14:52 :56
========================================
 UO[    6]    OFF -> ON 
Tick:   1717796
TB:     184408828
16-OCT-22 14:52 :56
========================================
 SO[    7]    OFF -> ON 
Tick:   1717763
TB:     184073392
16-OCT-22 14:52 :56
========================================
 UO[    8]    OFF -> ON 
Tick:   1717761
TB:     184067938
16-OCT-22 14:52 :56
========================================
 SO[    3]    ON  -> OFF
Tick:   1695685
TB:     -296889427
16-OCT-22 14:52 :08
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   1695683
TB:     -296940474
16-OCT-22 14:52 :08
========================================
 SO[    3]    OFF -> ON 
Tick:   1659110
TB:     -1161653883
16-OCT-22 14:50 :42
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   1659108
TB:     -1161669397
16-OCT-22 14:50 :42
========================================
 SO[    7]    ON  -> OFF
Tick:   1659075
TB:     -1162003990
16-OCT-22 14:50 :42
========================================
 UO[    8]    ON  -> OFF
Tick:   1659073
TB:     -1162016588
16-OCT-22 14:50 :42
========================================
 SO[    3]    ON  -> OFF
Tick:   1574949
TB:     -2047247197
16-OCT-22 14:49 :12
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   1574947
TB:     -2047267284
16-OCT-22 14:49 :12
========================================
 SO[    7]    OFF -> ON 
Tick:   1574788
TB:     -2049012385
16-OCT-22 14:49 :12
========================================
 UO[    8]    OFF -> ON 
Tick:   1574786
TB:     -2049036929
16-OCT-22 14:49 :12
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   1570341
TB:     -2095361394
16-OCT-22 14:49 :08
========================================
 SO[    3]    OFF -> ON 
Tick:   1570336
TB:     -2095404600
16-OCT-22 14:49 :08
========================================
 SO[    7]    ON  -> OFF
Tick:   1570308
TB:     -2095686049
16-OCT-22 14:49 :08
========================================
 UO[    8]    ON  -> OFF
Tick:   1570306
TB:     -2095711695
16-OCT-22 14:49 :08
========================================
 SO[    3]    ON  -> OFF
Tick:   1563651
TB:     2128506535
16-OCT-22 14:49 :00
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   1563649
TB:     2128485763
16-OCT-22 14:49 :00
========================================
 SO[    7]    OFF -> ON 
Tick:   1563203
TB:     2123805120
16-OCT-22 14:49 :00
========================================
 UO[    8]    OFF -> ON 
Tick:   1563201
TB:     2123799512
16-OCT-22 14:49 :00
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   1541830
TB:     1901484802
16-OCT-22 14:48 :38
========================================
 SO[    3]    OFF -> ON 
Tick:   1541825
TB:     1901434528
16-OCT-22 14:48 :38
========================================
 SO[    7]    ON  -> OFF
Tick:   1541797
TB:     1901154618
16-OCT-22 14:48 :38
========================================
 UO[    8]    ON  -> OFF
Tick:   1541795
TB:     1901134772
16-OCT-22 14:48 :38
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   1409733
TB:     514254233
16-OCT-22 14:46 :20
========================================
 SO[    3]    ON  -> OFF
Tick:   1409728
TB:     514211279
16-OCT-22 14:46 :20
========================================
 UO[    8]    OFF -> ON 
Tick:   1409222
TB:     508969485
16-OCT-22 14:46 :18
========================================
 SO[    7]    OFF -> ON 
Tick:   1409217
TB:     508933975
16-OCT-22 14:46 :18
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   1400101
TB:     414134264
16-OCT-22 14:46 :10
========================================
 SO[    3]    OFF -> ON 
Tick:   1400096
TB:     414109713
16-OCT-22 14:46 :10
========================================
 SO[    7]    ON  -> OFF
Tick:   1400068
TB:     413798394
16-OCT-22 14:46 :10
========================================
 UO[    8]    ON  -> OFF
Tick:   1400066
TB:     413779702
16-OCT-22 14:46 :10
========================================
 SO[    3]    ON  -> OFF
Tick:   1373125
TB:     127640788
16-OCT-22 14:45 :40
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   1373123
TB:     127621657
16-OCT-22 14:45 :40
========================================
 UO[    2]    ON  -> OFF
Tick:   1372612
TB:     122461491
16-OCT-22 14:45 :40
========================================
 UO[    6]    OFF -> ON 
Tick:   1372549
TB:     121796568
16-OCT-22 14:45 :40
========================================
 SO[    3]    OFF -> ON 
Tick:   1372544
TB:     121753174
16-OCT-22 14:45 :40
========================================
 UO[    8]    OFF -> ON 
Tick:   1372486
TB:     121157745
16-OCT-22 14:45 :40
========================================
 SO[    7]    OFF -> ON 
Tick:   1372481
TB:     121106256
16-OCT-22 14:45 :40
========================================
 SO[    3]    ON  -> OFF
Tick:   9763
TB:     -1196711377
16-OCT-22 14:22 :00
========================================
 UO[    6]    ON  -> OFF
Tick:   9761
TB:     -1196731317
16-OCT-22 14:22 :00
========================================
SSI[   10]    ON  -> OFF
Tick:   1545
TB:     -1280957738
16-OCT-22 14:21 :52
========================================
SSI[   10]    OFF -> ON 
Tick:   1083
TB:     -1285674422
16-OCT-22 14:21 :52
========================================
 UO[    2]    OFF -> ON 
Tick:   1060
TB:     -1285900399
16-OCT-22 14:21 :50
========================================
 UO[    6]    OFF -> ON 
Tick:   1046
TB:     -1287548774
16-OCT-22 14:21 :50
========================================
SSI[    1]    OFF -> ON 
SSI[    2]    OFF -> ON 
SSI[    3]    OFF -> ON 
SSI[    5]    OFF -> ON 
SSI[    6]    OFF -> ON 
SSI[    7]    OFF -> ON 
Tick:   1034
TB:     -1287671754
16-OCT-22 14:21 :50
========================================
 SO[    3]    OFF -> ON 
Tick:   1027
TB:     -1287685360
16-OCT-22 14:21 :50
========================================
 UO[   17]    OFF
 UO[   18]    OFF
 UO[   19]    OFF
 UO[   20]    OFF
 UO[   21]    OFF
 UO[   22]    OFF
 UO[   23]    OFF
 UO[   24]    OFF
 UO[   33]    OFF
 UO[   34]    OFF
 UO[   35]    OFF
 UO[   36]    OFF
Tick:   1019
TB:     -1287701720
16-OCT-22 14:21 :50
========================================
 AO[    1]    0
 AO[    3]    0
 AO[    3]    0
 AO[    5]    0
 AO[    5]    0
 AO[    7]    0
 UI[    1]    ON 
 UI[    2]    ON 
 UI[    3]    ON 
 UI[    4]    OFF
 UI[    5]    OFF
 UI[    6]    OFF
 UI[    7]    OFF
 UI[    8]    ON 
 UI[   17]    OFF
 UI[   18]    OFF
 UI[   19]    OFF
 UI[   20]    OFF
 UI[   21]    OFF
 UI[   22]    OFF
 UI[   23]    OFF
 UI[   24]    OFF
 UI[   33]    OFF
 UI[   34]    OFF
 UO[    1]    OFF
 UO[    2]    OFF
 UO[    3]    OFF
 UO[    4]    OFF
 UO[    5]    OFF
 UO[    6]    OFF
 UO[    7]    OFF
 UO[    8]    OFF
Tick:   1018
TB:     -1287702109
16-OCT-22 14:21 :50
========================================
 AI[   15]    0
 AI[   17]    0
 AI[   13]    0
 AI[   15]    0
 AI[   17]    0
 AI[   19]    0
 AI[   21]    0
 AI[   23]    0
Tick:   1017
TB:     -1287702512
16-OCT-22 14:21 :50
========================================
 AI[    5]    0
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
 AI[   13]    0
Tick:   1016
TB:     -1287786643
16-OCT-22 14:21 :50
========================================
 DO[   49]    OFF
 DO[   50]    OFF
 DO[   51]    OFF
 DO[   52]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   57]    OFF
 DO[   58]    OFF
 DO[   59]    OFF
 DO[   60]    OFF
 DO[   61]    OFF
 DO[   62]    OFF
 DO[   63]    OFF
 DO[   64]    OFF
 DO[   65]    OFF
 DO[   66]    OFF
 DO[   67]    OFF
 DO[   68]    OFF
 DO[   69]    OFF
 DO[   70]    OFF
 DO[   71]    OFF
 DO[   72]    OFF
 DO[   73]    OFF
 DO[   74]    OFF
 DO[   75]    OFF
 DO[   76]    OFF
 DO[   77]    OFF
 DO[   78]    OFF
 DO[   79]    OFF
 DO[   80]    OFF
 DO[   81]    OFF
 DO[   82]    OFF
 DO[   83]    OFF
 DO[   84]    OFF
 DO[   85]    OFF
 DO[   86]    OFF
 DO[   87]    OFF
 DO[   88]    OFF
 DO[   89]    OFF
 DO[   90]    OFF
 DO[   91]    OFF
 DO[   92]    OFF
 DO[   93]    OFF
 DO[   94]    OFF
 DO[   95]    OFF
 DO[   96]    OFF
 DO[   97]    OFF
 DO[   98]    OFF
 DO[   99]    OFF
 DO[  100]    OFF
 DO[  101]    OFF
 DO[  102]    OFF
 DO[  103]    OFF
 DO[  104]    OFF
 DO[  105]    OFF
 DO[  106]    OFF
 DO[  107]    OFF
 DO[  108]    OFF
 DO[  109]    OFF
 DO[  110]    OFF
 DO[  111]    OFF
 DO[  112]    OFF
 DO[  113]    OFF
 DO[  114]    OFF
 DO[  115]    OFF
 DO[  116]    OFF
 DO[  117]    OFF
 DO[  118]    OFF
 DO[  119]    OFF
 DO[  120]    OFF
 DO[  121]    OFF
 DO[  122]    OFF
 DO[  123]    OFF
 DO[  124]    OFF
 DO[  125]    OFF
 DO[  126]    OFF
 DO[  127]    OFF
 DO[  128]    OFF
 DO[  129]    OFF
 DO[  130]    OFF
 DO[  131]    OFF
 DO[  132]    OFF
 DO[  133]    OFF
 DO[  134]    OFF
 DO[  135]    OFF
 DO[  136]    OFF
 DO[  137]    OFF
 DO[  138]    OFF
 DO[  139]    OFF
 DO[  140]    OFF
 DO[  141]    OFF
 DO[  142]    OFF
 DO[  143]    OFF
 DO[  144]    OFF
 AI[    1]    0
 AI[    3]    0
Tick:   1015
TB:     -1287795746
16-OCT-22 14:21 :50
========================================
 DI[   65]    OFF
 DI[   66]    OFF
 DI[   67]    OFF
 DI[   68]    OFF
 DI[   69]    OFF
 DI[   70]    OFF
 DI[   71]    OFF
 DI[   72]    OFF
 DI[   73]    OFF
 DI[   74]    OFF
 DI[   75]    OFF
 DI[   76]    OFF
 DI[   77]    OFF
 DI[   78]    OFF
 DI[   79]    OFF
 DI[   80]    OFF
 DI[   81]    OFF
 DI[   82]    OFF
 DI[   83]    OFF
 DI[   84]    OFF
 DI[   85]    OFF
 DI[   86]    OFF
 DI[   87]    OFF
 DI[   88]    OFF
 DI[   89]    OFF
 DI[   90]    OFF
 DI[   91]    OFF
 DI[   92]    OFF
 DI[   93]    OFF
 DI[   94]    OFF
 DI[   95]    OFF
 DI[   96]    OFF
 DI[   97]    OFF
 DI[   98]    OFF
 DI[   99]    OFF
 DI[  100]    OFF
 DI[  101]    OFF
 DI[  102]    OFF
 DI[  103]    OFF
 DI[  104]    OFF
 DI[  105]    OFF
 DI[  106]    OFF
 DI[  107]    OFF
 DI[  108]    OFF
 DI[  109]    OFF
 DI[  110]    OFF
 DI[  111]    OFF
 DI[  112]    OFF
 DI[  113]    OFF
 DI[  114]    OFF
 DI[  115]    OFF
 DI[  116]    OFF
 DI[  117]    OFF
 DI[  118]    OFF
 DI[  119]    OFF
 DI[  120]    OFF
 DI[  121]    OFF
 DI[  122]    OFF
 DI[  123]    OFF
 DI[  124]    OFF
 DI[  125]    OFF
 DI[  126]    OFF
 DI[  127]    OFF
 DI[  128]    OFF
 DI[  129]    OFF
 DI[  130]    OFF
 DI[  131]    OFF
 DI[  132]    OFF
 DI[  133]    OFF
 DI[  134]    OFF
 DI[  135]    OFF
 DI[  136]    OFF
 DI[  137]    OFF
 DI[  138]    OFF
 DI[  139]    OFF
 DI[  140]    OFF
 DI[  141]    OFF
 DI[  142]    OFF
 DI[  143]    OFF
 DI[  144]    OFF
 DO[   21]    OFF
 DO[   22]    OFF
 DO[   23]    OFF
 DO[   24]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   29]    OFF
 DO[   30]    OFF
 DO[   31]    OFF
 DO[   32]    OFF
 DO[   33]    OFF
 DO[   34]    OFF
 DO[   35]    OFF
 DO[   36]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   45]    OFF
 DO[   46]    OFF
 DO[   47]    OFF
 DO[   48]    OFF
Tick:   1014
TB:     -1287796305
16-OCT-22 14:21 :50
========================================
 SI[    0]    ON 
 SI[    1]    OFF
 SI[    2]    ON 
 SI[    3]    ON 
 SI[    4]    OFF
 SI[    5]    OFF
 SI[    6]    OFF
 SI[    7]    OFF
 SI[    8]    ON 
 SI[    9]    ON 
 SI[   10]    OFF
 SI[   11]    OFF
 SI[   12]    OFF
 SI[   13]    OFF
 SI[   14]    OFF
 SI[   15]    OFF
 SO[    0]    OFF
 SO[    1]    OFF
 SO[    2]    OFF
 SO[    3]    OFF
 SO[    4]    OFF
 SO[    5]    OFF
 SO[    6]    OFF
 SO[    7]    OFF
 SO[    8]    OFF
 SO[    9]    OFF
 SO[   10]    OFF
 SO[   11]    OFF
 SO[   12]    OFF
 SO[   13]    OFF
 SO[   14]    OFF
 SO[   15]    OFF
 RI[    1]    OFF
 RI[    2]    OFF
 RI[    3]    OFF
 RI[    4]    OFF
 RI[    5]    OFF
 RI[    6]    OFF
 RI[    7]    OFF
 RI[    8]    OFF
 RO[    1]    OFF
 RO[    2]    OFF
 RO[    3]    OFF
 RO[    4]    OFF
 RO[    5]    OFF
 RO[    6]    OFF
 RO[    7]    OFF
 RO[    8]    OFF
SSI[    1]    OFF
SSI[    2]    OFF
SSI[    3]    OFF
SSI[    4]    OFF
SSI[    5]    OFF
SSI[    6]    OFF
SSI[    7]    OFF
SSI[    8]    OFF
SSI[    9]    OFF
SSI[   10]    OFF
SSI[   11]    OFF
 DI[   19]    OFF
 DI[   20]    OFF
 DI[   21]    OFF
 DI[   22]    OFF
 DI[   23]    OFF
 DI[   24]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   27]    OFF
 DI[   28]    OFF
 DI[   29]    OFF
 DI[   30]    OFF
 DI[   31]    OFF
 DI[   32]    OFF
 DI[   33]    OFF
 DI[   34]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   43]    OFF
 DI[   44]    OFF
 DI[   45]    OFF
 DI[   46]    OFF
 DI[   47]    OFF
 DI[   48]    OFF
 DI[   49]    OFF
 DI[   50]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
 DI[   57]    OFF
 DI[   58]    OFF
 DI[   59]    OFF
 DI[   60]    OFF
 DI[   61]    OFF
 DI[   62]    OFF
 DI[   63]    OFF
 DI[   64]    OFF
Tick:   1013
TB:     -1287796777
16-OCT-22 14:21 :50
