ERRMOT.LS      Robot Name ROBOT 16-OCT-22 15:30:12  

1" 16-OCT-22 14:52:56 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
2" 16-OCT-22 14:49:12 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
3" 16-OCT-22 14:49:00 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
4" 16-OCT-22 14:45:40 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
5" 15-OCT-22 19:13:54 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
6" 15-OCT-22 18:13:56 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
7" 15-OCT-22 18:13:12 " MCTL-014 Waiting for Servo ready                  " MCTL-014 Waiting for Servo ready                  " WARN                          00000000" 
