ERRMOT.LS      Robot Name ROBOT 15-OCT-22 19:31:28  

1" 15-OCT-22 19:13:54 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
2" 15-OCT-22 18:13:56 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
3" 15-OCT-22 18:13:12 " MCTL-014 Waiting for Servo ready                  " MCTL-014 Waiting for Servo ready                  " WARN                          00000000" 
